### ISSUE TITLE
New KinematicEvaluatorSet causes segfault in multibody_sim

### ISSUE THREAD

**Issue by yangwill** [DAIRLab/dairlib#191]
The new update to `KinematicEvaluatorSet` causes `multibody_sim` to throw a warning `Plant in KinematicEvaluatorSet has an associated SceneGraph. This may introduce undesired contact forces when using EvalActiveSecondTimeDerivative, EvalFullSecondTimeDerivative, and CalcTimeDerivativesWithForWithForce` and segfault.

Looking into the issue.

**Comment by yminchen** [comment]
I have solved it in #186

**Comment by mposa** [comment]
Ah, this is because I changed `KinematicEvaluatorSet` to use MBP's dynamics calculations (more foolproof than re-creating them on our end). However, we _don't_ want MBP to compute contact forces. The best approach is to pass a MBP into `KinematicEvaluatorSet` that does not have an associated SceneGraph.

I'm not sure what the segfault is, but it looks like @yminchen has resolved that.

**Comment by yangwill** [comment]
Fixed in #186, closing the issue
